### ISSUE TITLE
32: Aktualisierung der Kostendaten, wenn sich Produkt ändert

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#16]
Falls Wärmeerzeuger, Hausübergabestationen, Pufferspeicher, Wärmerückgewinnung und Rauchgasreinigung im geöffneten Tab im nachhinein geändert werden, so ändern sich die Daten für die Wirtschaftlichkeitsberechnung nicht mit.

Die Daten sollen immer geändert werden, es sei denn, ein Wert ist nicht vorhanden (Preis bei Firmenprodukten)

auf den Dialog könnte man verzichten -> neue Auswahl -> Daten aktualisieren (Preis nur, wenn vorhanden)  (Kommentar aus dem Meeting)

**Comment by wscarmen** [comment]
Preis wird jetzt immer vom neuen Produkt übernommen (auch wenn er leer ist), aber das ist ok, weil es konsistent ist und der Benutzer auf fehlende Investkosten durch eine Rotmarkierung aufmerksam gemacht wird
