### ISSUE TITLE
51: Wirtschaftlichkeit: Anschlusskosten in den Projekt-Kosteneinstellungen werden nicht berücksichtigt

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#23]
Sie müssten jedoch bei der Berechnung der Wirtschaftlichkeit bei den kapitalgebundenen Kosten (Zeile 2, mit und ohne Förderung) vor deren Berechnung von den zugrundegelegten Investitionskosten abgezogen werden. Die angezeigten Investitionskosten bleiben unverändert.

diese werden als Summe für alle Abnehmer angeben

**Comment by wscarmen** [comment]
- [ ] Die Bezeichnung soll von "Einmalige Anschlusskosten" in "Anschlusskostenbeiträge" geändert werden
- [ ] Der eingegebene Wert soll in der Tabelle "Wirtschaftlichkeit" angezeigt werden (siehe #75 )
