### ISSUE TITLE
11: Wartungszeiten/ Stillstandszeiten für Wärmeerzeuger

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#3]
> Betriebsunterbrechungen werden in einer Tabelle (wie z.B. Verbrauchsdaten eines Abnehmers) erfasst. Sie können stundengenau angegeben werden, z.B. bei einer Wartung „6.März, 9 Uhr - 11 Uhr“. Sollte bei einem BHKW z.B. eine wöchentliche Wartung notwendig sein, müssen 52 Betriebsunterbrechungen eingetragen werden.

-> Jede Unterbrechung braucht einen Start- und Endzeitpunkt (stundengenau); vielleicht optional auch eine Bezeichnung
-> Tabelle: kleiner Dialog zur Auswahl von Start- und Endzeitpunkt

Zurückgestellt: Import über CSV-Datei

> Der Import einer csv-Datei mit Stundenangaben ist möglich. Die Datei hat mindestens 2 Spalten und ist wie folgt aufgebaut: 1: Beginn-Stunde des Unterbrechung (z.B. 5410); 2: Ende-Stunde des Unterbrechung (z.B. 5414)

g.A.: 16h

**Comment by wscarmen** [comment]
Bei der Berechnung des Nutzungsgrads muss die Stillstandszeit von der Nutzungsdauer abgezogen werden (Siehe Konzept Wärmeerzeuger, Seite 6).
