### ISSUE TITLE
Projekt-Kosteneinstellungen als eigener Unterpunkt im Projektbaum zwischen Investitionen und Ergebnissen

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#39]
Benutzer finden sie oft nicht

**Comment by msrocka** [comment]
@wscarmen eine andere Möglichkeit wäre hier vielleicht die Kosteneinstellungen direkt auf die Projektseite zu verschieben, also unter den allgemeinen Projektinformationen (die Seite ist ja noch recht leer)

**Comment by wscarmen** [comment]
Habe dazu neuen Issue erfasst.
