### ISSUE TITLE
Beim Projektvergleich sollen weitere Ergebnisse berücksichtigt werden

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#40]

**Comment by wscarmen** [comment]
Bei den weiteren Kennzahlen stehen in der Zeile "Netzverluste" die Gesamtverluste. Es wäre schön, wenn in den Graphiken zwischen den Balken ein kleiner Abstand wäre.

**Comment by msrocka** [comment]
Es sollten jetzt die tatsächlich die Netzverluste angezeigt werden. Die Bezeichnungen wurden auch angepasst. Leider geht das mit den Balkenabständen nicht so einfach mit der derzeitigen Chart-API (http://www.swtchart.org/); die Balken sind dann wiederum sehr breit.

**Comment by wscarmen** [comment]
- [ ] Es sollen generell nur Ergebnisse mit Förderung verglichen werden, d.h. die Tabelle Wirtschaftlichkeit ohne Förderung kann wegfallen und die Balken ohne Förderung bei der Graphik der Wärmegestehungskosten
- [ ] Die Tabelle zur Wirtschaftlichkeit soll genauso aufgebaut sein bei den Ergebnissen
- [ ] Die Graphiken zu den Wärme- und Stromerlösen sollen in einer Graphik in einem gestapelten Balkendiagramm mit der Überschrift "Erlöse" zusammengefasst werden
- [ ] Die vier Kostenarten sollen in einer Graphik in einem gestapelten Balkendiagramm mit der Überschrift "Kosten" dargestellt werden (Anordnung: vor der Graphik "Erlöse")

**Comment by wscarmen** [comment]
Bei jeder Neuberechnung des Ergebnisvergleichs wird ein weiterer Tab geöffnet. Das kann mit der Zeit verwirrend werden. Daher soll wie bei den Ergebnissen bei einer Neuberechnung der Tab mit den alten Ergebnissen geschlossen werden.
Der Jahresüberschuss kann auch negativ werden oder je nach Variante knapp über oder unter Null liegen. In der Graphik wird die x-Achse dann trotzdem ganz unten gezeichnet. Schöner wäre es, wenn die x-Achse dann auf Höhe der Null liegen würde.

**Comment by msrocka** [comment]
Es wird jetzt immer die alte Vergleichsansicht geschlossen, wenn eine neue geöffnet wird. Das mit der Null-Achse ist etwas schwieriger, da dies in der [Chart-API](http://www.swtchart.org/doc/index.html) nicht vorgesehen ist. Man könnte zwar irgendwie eine Linie darüber zeichnen, aber das ist dann durch den Aufwand nicht mehr gedeckt.
