### ISSUE TITLE
Updatefunktion für Datenpakete aus Version 1.0

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#53]
Das Aktualisieren von Datenbanken wird nicht unterstützt, aber Datenpakete aus der Version 1.0 soll man in die neue Version importieren können:

* [x] Versionsnummer für die Datenbank hinzufügen. Stimmt diese nicht mit der aktuellen Version überein bzw. ist nicht Vorhanden, wird eine entsprechende Meldung angezeigt (vielleicht einfache Versionsdatei im Datenbankverzeichnis im gleichen Format, wie im Datenpaket; siehe unten)
* [x] Versionsnummer bei den Datenpaketen hinzufügen; als JSON-Datei mit Metadaten (ähnlich wie package.json). Prüfen dieser Datei beim Import: entsprechenden Updatefilter im Datenpaket setzen (die JSON-Objekte werden dadurch gefiltert/aktualisiert; in späteren Versionen kann so ein Filter dann auch eine Kette von Filtern sein). Beim Schreiben eines Pakets müssen die Metadaten zu dem Paket hinzugefügt werden.
* [x]  Holz/Pelletsbrennstoffmengen bei verbrauchsbezogenen Abnehmern müssen in Tonnen umgerechnet werden, wenn nötig (z.B. Prüfen der Einheit in der JSON-Datei gegen die Einheit in der Datenbank und dann umrechnen)
* [x] jeder `Producer` braucht eine `FuelSpec`
* [x] jeder `Producer` braucht eine `ProductGroup`, diese muss beim Update gesetzt werden und wird aus dem `Boiler` gezogen

### Defaultwerte für neue Folder

* [x] Frostschutztemperatur 
* [ ] Lambda-Wert für Pufferspeicherdämmung

**Comment by msrocka** [comment]
Aufwand für initiales Aufsetzen; einzelne Updatefunktionen werden bei den einzelnen Tasks hineingerechnet

**Comment by wscarmen** [comment]
Die Umrechnung bei Pellets von kg in t funktioniert noch nicht. Eine Umrechnung ist bei Abnehmern nötig, die bisher Pellets verwendet haben und bei der Preisangabe für den Brennstoff bei Pelletkesseln.
