### ISSUE TITLE
Anpassen der Excelexporte

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#59]
Da sich die Ergebnisse geändert haben müssen entsprechend auch die Excel-Exporte angepasst werden

**Comment by wscarmen** [comment]
Bei einem Testprojekt (kommt per Mail) bricht der Export mit einem Fehler ab.

**Comment by wscarmen** [comment]
Bei einer KWK-Anlage wird der Nutzungsgrad falsch exportiert (Beispielprojekt kommt per E-Mail)
