### ISSUE TITLE
14: Wärmeverteilung: Pufferspeicherverluste in Abhängigkeit von der Ladung berücksichtigen

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#6]
%-Wert ist voreingestellt; Verluste werden auch im Verluste-Diagramm angezeigt
ein Prozentwert, aber muss im Ergebnis mit angezeigt werden etc.

**Comment by wscarmen** [comment]
Die Pufferspeicherverluste sollen in den Ergebnissen auch bei den Abnehmern (nach den Netzverlusten) aufgenommen werden.

**Comment by wscarmen** [comment]
Für die Berechnung des Wärmeverlusts wird die Oberfläche des Pufferspeichers mit dem U-Wert der Dämmung multipliziert, der daraus ermittelte Wärmeverlust in W/K muss dann mit dem Temperaturunterschied zwischen der durchschnittlichen Puffertemperatur und der durchschnittlichen Raumtemperatur multipliziert werden. Dabei wird die durchschnittliche Puffertemperatur nach dem Einsatz der Kessel verwendet. Die Schritte sehen im Einzelnen wie folgt aus:

**Ermittlung der Oberfläche** (zur Vereinfachung wird angenommen, dass der Puffer eine Zylinderform besitzt):
Radius = (Durchmesser – 2 * Isolierstärke) / 2
Höhe = (Höhe – 2 * Isolierstärke)
Oberfläche = 2 * Radius ^ 2 * Pi + 2 * Radius * Pi * Höhe
**Ermittlung des U-Werts:**
U-Wert = Lambda-Wert / Isolierstärke (in m)
**Ermittlung der durchschnittlichen Puffertemperatur:**
Untere Ladetemp. + Ladestand (in %) * (maximale Ladetemp. – untere Ladetemp.)
**Durchschnittliche Raumtemperatur:** 20°C (Annahme)

**Beispiel:**

- Pufferspeicher_10000 von Bosch: Volumen = 10.000l, Durchmesser (mit Isol.) = 2.000 mm, Höhe (mit Isol.) = 3.600 mm, Isolierstärke: 100 mm (aus Produktdatenbank)
- Max. Ladetemp. 95°C, untere Ladetemp. 80°C, Lambda = 0,04 W/m*K (aus Benutzereingaben)
- Ladestand: 50% (aus Algorithmus)

Damit ergibt sich:

Oberfläche = 2 * (0,9 m) ^ 2 * Pi + 2 * 0,9 m * Pi * 3,4 m = 5,09 m2 + 19,23 m2 = 24,32 m2
U-Wert = 0,04 W/m*K / 0,1 m = 0,4 W/ m2*K
Puffertemperatur = 80°C + 0,5 * (95°C – 80°C) = 87,5°C

Also ergibt sich als durchschnittliche Verlustleistung:
24,32 m2 * 0,4 W/ m2*K * (87,5°C – 20°C) = 656,64 W

Damit beträgt der Wärmeverlust in dieser Stunde 0,6564 kWh.

**Comment by msrocka** [comment]
* es muss dann auch immer ein Produkt ausgewählt werden (das Volumenfeld im Heiznetz kann entfallen)
* die Maßangaben müssen Pflichtfelder werden (auch für die Standardprodukte, wo das derzeit noch nicht der Fall ist)

**Comment by wscarmen** [comment]
- [ ] Es scheint so, dass die Pufferspeicherverluste 0 sind, wenn die freie Kapazität des Puffers nach Kesseleinsatz größer gleich der gesamten Kapazität sind. Aber auch da ist noch ein Verlust vorhanden. Ein Beispiel und ein Exceltool dazu kommt per Mail.
- [ ] Nach einigen Diskussionen mit Kollegen möchen wir die Gefahr jetzt doch ausschließen, dass durch Änderung des Volumens ein falsches Ergebnis für die Verluste herauskommt. Bitte deswegen das Eingabefeld für das Volumen in ein graues Infofeld umwandeln. Eine Änderung des Volumens ist dann nur noch durch eine Änderung des Produkts möglich. Es kann aber weiterhin komplett ohne Puffer gerechnet werden.
- [ ] Bei der Erfassung eines Puffers in der Datenbank müssen die Felder Höhe, Durchmesser und Isolierung zu Mussfeldern gemacht werden.

**Comment by msrocka** [comment]
[Test Pufferverluste.xlsx](https://github.com/GreenDelta/Sophena/files/2547889/Test.Pufferverluste.xlsx)

**Comment by wscarmen** [comment]
Bei einer Dämmstärke von 0 mm müssten rein rechnerisch unendlich hohe Verluste auftreten. Im Moment werden dann aber überhaupt keine Verluste ausgewiesen. Daher soll pragmatisch bei einer hinterlegten Dämmstärke von 0 mm eine Dämmstärke von 1 mm angenommen werden.

**Comment by wscarmen** [comment]
Die minimale Dämmstärke funktioniert bei meinen Tests noch nicht.
