### ISSUE TITLE
Primärenergiefaktor beim Strom

### ISSUE THREAD

**Issue by wscarmen** [GreenDelta/Sophena#64]
Primärenergiefaktor und Treibhausgasemissionen soll für Wärmeerzeuger-Stromverbrauch, Heizwerk-Stromverbrauch und KWK-Stromerzeugung unterschiedlich wählbar sein.

Dazu werden bei den Energieträgern zwei verschiedene Arten von Strom eingestellt:
- Strom (Strommix) PEF=1,8 CO2 489 g/kWh
- Strom (Verdrängungsstrommix) PEF=2,8 624 g/kWh

Der Benutzer kann den verwendeten Strom dann selbst einstellen:
- Bei einem Erzeuger (z.B. Wärmepumpe) über die Wahl des Energieträgers
- Bei einem BHKW über eine neues Feld "Erzeugter Strom"
- Beim Stromeigenverbrauch im Heizwerk über ein neues Feld "Verbrauchter Strom", bei dem "Strom (Erzeugung)" voreingestellt wird

**Comment by wscarmen** [comment]
Wenn möglich, sollen folgende Voreinstellungen gemacht werden:
Eigenstrombedarf: Strom (Verdrängungsstrommix)
KWK Erzeugter Strom: Strom (Verdrängungsstrommix)
Strom als Energieträger für Wärmeerzeuger (z.B. bei Wärmepumpe): Strom (Strommix)

**Comment by msrocka** [comment]
Die sauberste Lösung wäre hier, wenn man dies in die globalen Einstellungen übernimmt. Der Begriff `Kosteneinstellungen` passt dann aber auch immer weniger (vielleicht können wir das dann einfach `Einstellungen` nennen).
