### ISSUE TITLE
Einführung eines Sommermodus bei Grundlast-Wärmeerzeugern

### ISSUE THREAD

**Issue by wscarmen** [GreenDelta/Sophena#66]
In der Simulation ist derzeit die Abbildung der Sommerphase unpassend. Im Sommer laufen Grundlast-Kessel normalerweise im Ein-/Aus-Modus, d.h. sie heizen den Puffer vollständig auf und gehen dann aus, bis der Puffer wieder leer ist. Das kann wie folgt abgebildet werden:

1) Der Wärmeerzeuger auf Rang 1 befindet sich im Sommermodus, wenn die anliegende Last geringer ist als seine minimale Leistung.
2) Wenn in einer Sommerstunde die gesamte Last aus dem Puffer gedeckt werden kann, wird ein Flag auf "Pufferentladen" gestellt. Danach wird solange aus dem Puffer geheizt, bis dieser leer ist.
3) Wenn in einer Sommerstunde das Flag auf "Pufferentladen" steht und die Restladung des Puffers nicht mehr reicht, wird das Flag auf "Pufferladen" gesetzt und aus dem Pufferspeicher wird solange nicht mehr geheizt, bis er voll ist.
4) In einer Winterstunde bleibt alles beim alten, auch wenn sie zwischen Sommerstunden liegt.

**Comment by msrocka** [comment]
Der geschätzte Aufwand beinhaltet Testen, Absprachen und Korrekturen

**Comment by wscarmen** [comment]
Diesen Punkt bitte zurückstellen, wenn es vom Budget knapp wird ...

**Comment by wscarmen** [comment]
- [ ] Beim Testen ist mir aufgefallen, dass es (sehr selten) dazu kommen kann, dass der Erzeuger von Rang 1 nicht läuft und stattdessen der von Rang 2 (wenn dieser stärker teillastfähig ist und dann in einer Stunde noch in den Puffer passt, der von Rang 1 aber nicht). 
Das darf nicht sein, d.h. beim Sommermodus muss von Pufferladen auf Pufferentladen umgestellt werden, wenn die freie Kapazität des Puffers geringer als die minimale Leistung des Erzeugers von Rang 1 ist. 

- [ ] Steht oben nicht so direkt drin, deshalb zur Klarstellung: Der Sommermodus betrifft nur "normale" Wärmeerzeuger auf Rang 1, wenn auf Rang 1 ein Erzeugerlastgang ist, gibt es keinen Sommermodus.
