### ISSUE TITLE
Pufferspeicherangaben im Ergebnis und andere (kleinere) Punkte

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#67]
* [x] Zur Heizwertberechnung: Der Heizwert bei 0% Wassergehalt stimmt jetzt, allerdings sind jetzt die Werte bei vorhandenem Wassergehalt zu hoch. Da scheint irgendwo ein Faktor an der falschen Stelle zu stehen… Zum Testen können folgende Wert verwendet werden: Fichte mit Wassergehalt 20% hat als Heizwert etwa 4.020 kWh/t. Bei der Eingabe von Srm stimmt es weiterhin.
* [x] Die Voreinstellung von 1 % beim Aschegehalt bei importierten Holzbrennstoffen ist ok, bei den Energieträger-Daten ist allerdings ein kleiner Fehler drin: bei Pappel muss der Aschegehalt 2 % sein.
* [x] Bei den Ergebnissen ist aufgefallen, dass beim Pufferspeicher immer das Volumen des ausgewählten Produkts erscheint und nicht das im Projekt eingegebene. Außerdem werden dort Wärmemenge und Anteil nicht mehr angezeigt.
* [x] In gewissen Konstellationen werden in der Graphik "Verwendung Brennstoffenergie" (weitere Ergebnisse) die Verteilungsverluste nicht angezeigt.

**Comment by wscarmen** [comment]
Bei Pappel ist der Aschegehalt immer noch 1% und nicht 2 %
