### ISSUE TITLE
Filtermöglichkeit nach Größenklasse bei Wärmeerzeugern

### ISSUE THREAD

**Issue by wscarmen** [GreenDelta/Sophena#69]
Nachdem es in der neuen Version noch mehr Hersteller gibt, wird die Liste immer länger, in der man seinen gewünschten Wärmeerzeuger finden muss. Daher wäre eine zusätzliche Filtermöglichkeit nach Größenklasse hilfreich. Größenklassen könnten z.B. sein:
bis 150 kW
150-350 kW
350-750 kW
über 750 kW

**Comment by msrocka** [comment]
Fragen:

* [ ] Soll nur maximale thermische Leistung in dem Filter berücksichtigt werden oder auch die minimale?
* [ ] Bei BHKWs auch nach thermischer Leistung filtern (es wird die elektr. angezeigt; min/max)?

**Comment by wscarmen** [comment]
Bei der Auswahl werden die Wärmeerzeuger nicht nach der angezeigten Nennleistung (=maximale Leistung) sortiert, sondern - so wie es aussieht - nach der minimalen Leistung. Bei den KWK-Anlagen ist es ok.
