### ISSUE TITLE
Überarbeitung der Infotexte

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#8]
Dieser Text?

> Kosten für Übergeordnete Mess-und Regeltechnik liegen nicht in der gleichen Größenordnung wie Hydraulik + Elektroinstallation! Übergeordnete Mess- und Regeltechnik lassen sich überschlägig mit 15-20 % der Kosten für die Technik ohne Biomassekessel berechnen (das sind ggf. Spitzenlastkessel, Hydraulik- und Elektroinstallation, Wärmenetz-Technik, Pufferspeicher, evtl. BHKW).

**Comment by wscarmen** [comment]
Siehe Exceldatei:

- [ ] Heizhaus-Technik: Text ändern
- [ ] neu bei Pufferspeicher und Wärmepumpen
