### ISSUE TITLE
Integration der neuen Produktbereiche

### ISSUE THREAD

**Issue by wscarmen** [GreenDelta/Sophena#83]
Im Zuge der Erweiterungen sind 5 neue Produktbereiche eingeführt worden. Hierbei ist noch folgende zu tun:

**Wärmepumpe**: siehe #78 
**Solarthermische Anlage**: Anzeige in den Investitionen und im Menü
**Elektrischer Wärmeerzeuger**: Anzeige in den Investitionen und im Menü; Parameterrecherche (C.A.R.M.E.N.)
**Sonstige Wärmequelle**: heißt in der Tabelle "Produktgruppen" "Andere Wärmequellen", bitte dort umbenennen; soll die gleichen Parameter bekommen wie die Produktgruppe "Hydraulik"
**Sonstiges Zubehör**: Anzeige in den Investitionen und im Menü; weitere Produktgruppen definieren und Parameterrecherche (C.A.R.M.E.N.)

**Comment by msrocka** [comment]
Das Menü und die Investitionsbereiche sollten jetzt vollständig sein:

![image](https://user-images.githubusercontent.com/3520062/48903304-6cd2f780-ee5b-11e8-9994-4313f2182ad0.png)

**Comment by wscarmen** [comment]
- [ ] Solarthermische Anlage, Elektrischer Wärmeerzeuger, Sonstige Wärmequelle: Die Erfassung der Kosten geschieht beim Erzeugerlastgang, diese Werte sollen in die Investitionen übernommen werden, dort sollen keine Eintragungen möglich sein.
- [ ] Sonstiges Zubehör fehlt noch
