### ISSUE TITLE
Der Ort eines Abnehmers kann nicht mehr über die Karte gesetzt werden

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#89]
Das liegt wahrscheinlich an der Aktualisierung der Eclipse-Plattform und das Zusammenspiel mit dem JavaFX-Browser. Wir könnten hier versuchen auf den Systembrowser zu wechseln (müssen dann aber schauen, ob hier die Proxy-Einstellungen übernommen werden), da die Integration vom JavaFX-Browser generell immer wieder Probleme macht (und auch in Java 10 aus dem JDK entfernt wurde).

https://bugs.openjdk.java.net/browse/JDK-8170085
https://stackoverflow.com/a/53618875

**Comment by wscarmen** [comment]
Hat beim Test auf dem Bürorechner funktioniert.
