### ISSUE TITLE
Wärmebelegungsdichte ohne Pufferspeicherverluste berechnen

### ISSUE THREAD

**Issue by wscarmen** [GreenDelta/Sophena#93]
Die Wärmebelegungsdichte berechnet sich aus dem Wert der „Genutzten Wärme“ dividiert durch die Trassenlänge.
Derzeit werden die Pufferspeicherverluste als "Genutzte Wärme" angesehen, so dass die Wärmebelegungsdichte bei steigenden Pufferspeicherverlusten größer wird. Die Wärmebelegungsdichte muss aber unabhängig von den Pufferspeicherverlusten sein!

**Comment by wscarmen** [comment]
Beim Test war die Wärmebelegungsdichte immer noch nicht unabhängig von den Pufferspeicherverlusten, sie ist jetzt minimal kleiner geworden bei steigenden Pufferspeicherverlusten.

**Comment by msrocka** [comment]
Wie besprochen, werden hier zunächst die Pufferspeicherverluste (und auch Netzverluste) stundenweise zusammengezählt und dann als Block von der erzeugten Wärme abgezogen. Dabei kann es beim Ändern der Pufferspeicherverluste zu kleinen Rechenungenauigkeiten kommen.
