### ISSUE TITLE
Willkommensseite dynamisch generieren

### ISSUE THREAD

**Issue by wscarmen** [GreenDelta/Sophena#97]
Auf der Willkommensseite werden u.a. die Logos der Hersteller angezeigt. Wenn ein neuer Hersteller als Sponsor dazukommt, muss deswegen im Moment auch die Software geändert werden.

Deswegen soll die Willkommensseite dynamisch aus der Produktdatenbank erzeugt werden.

**Comment by msrocka** [comment]
Ich habe eine erste Version dafür gebaut und das scheint ganz gut zu funktionieren. Braucht man dann auch eine definierte Ordnung für die Logos oder nach welchen Kriterien sollen diese dann in der Startseite sortiert werden? In jedem Fall ist dafür ein Datenbank-Update nötig. Man kann dann also eine Sophena 2.0 Datenbank nicht einfach mit einer Sophena 2.1 Version öffnen, sondern muss, wie von 1.0 -> 2.0, die Daten exportieren und dann importieren. Auch sind die Hersteller beim ersten Öffnen der Anwendung dann nicht sichtbar, sondern erst, wenn die Produktdaten importiert wurden. Ist das so gedacht?

**Comment by wscarmen** [comment]
Die Sortierung erfolgt im Prinzip nach der Anzahl der eingebrachten Produktkategorien. Wahrscheinlich ist aber eine Spalte mit der Sortierreihenfolge in der Datenbank am besten.
